// Sample data
const readingData = {
  ongoing: [
    {
      id: 1,
      title: "Dukedom's Legendary Prodigy",
      author: "Author Name",
      cover: "/anime-character-purple-dark.jpg",
      currentChapter: 301,
      totalChapters: 450,
      progress: 67,
      lastRead: "2 hours ago",
      rating: 4.8,
    },
    {
      id: 2,
      title: "Demonic Frontline Flying Dragon",
      author: "Author Name",
      cover: "/anime-dragon-battle.jpg",
      currentChapter: 359,
      totalChapters: 400,
      progress: 90,
      lastRead: "5 hours ago",
      rating: 4.6,
    },
    {
      id: 3,
      title: "I Became a Motivational Demon Sword",
      author: "Author Name",
      cover: "/anime-sword-martial-arts.jpg",
      currentChapter: 241,
      totalChapters: 350,
      progress: 69,
      lastRead: "1 day ago",
      rating: 4.7,
    },
  ],
  bookmarked: [
    {
      id: 4,
      title: "The Time-Limited Baby Doctor",
      novelTitle: "The Time-Limited Baby Doctor Doesn't Hide",
      chapter: 120,
      savedAt: "3 days ago",
      cover: "/anime-doctor-medical.jpg",
    },
    {
      id: 5,
      title: "Academy Retirement Diary",
      chapter: 45,
      savedAt: "1 week ago",
      cover: "/anime-academy-school.jpg",
    },
  ],
  toRead: [
    {
      id: 6,
      title: "Smartphone in Murim Academy",
      author: "Author Name",
      cover: "/anime-academy-modern.jpg",
      chapters: 163,
      rating: 4.5,
    },
    {
      id: 7,
      title: "30 Years Have Passed Since the...",
      author: "Author Name",
      cover: "/anime-time-travel.jpg",
      chapters: 120,
      rating: 4.4,
    },
  ],
  completed: [
    {
      id: 8,
      title: "I Became An Academy...",
      author: "Author Name",
      cover: "/anime-academy-golden.jpg",
      totalChapters: 500,
      completedAt: "2 months ago",
      rating: 4.9,
    },
    {
      id: 9,
      title: "Omniscient First-Person's Viewpoint",
      author: "Author Name",
      cover: "/anime-perspective-view.jpg",
      totalChapters: 241,
      completedAt: "3 months ago",
      rating: 4.7,
    },
  ],
};
